import type { AgentProfileSkeleton } from '@orion/contracts';

type DeepReadonly<Value> = Value extends readonly (infer Item)[]
  ? readonly DeepReadonly<Item>[]
  : Value extends object
    ? { readonly [Key in keyof Value]: DeepReadonly<Value[Key]> }
    : Value;

function deepFreeze<Value>(value: Value): DeepReadonly<Value> {
  if (value !== null && typeof value === 'object') {
    for (const nested of Object.values(value)) {
      deepFreeze(nested);
    }
    Object.freeze(value);
  }

  return value as DeepReadonly<Value>;
}

const seedSkeletonDefinitions: AgentProfileSkeleton[] = [
  {
    id: 'atlas',
    version: 1,
    name: 'Atlas',
    displayName: 'Atlas — Strategy and Business Model',
    description: 'Executive strategy advisor for business models, portfolios, and growth roadmaps.',
    provider: 'openai',
    model: 'gpt-5.6-sol',
    fallbackModels: [
      { provider: 'anthropic', model: 'claude-opus-4-8' },
      { provider: 'openai', model: 'gpt-5.6-terra' },
    ],
    reasoningEffort: 'high',
    permissionTemplate: 'advisor',
    permissions: {
      networkReadAllowed: true,
      projectReadAllowed: true,
      artifactWriteAllowed: true,
      worktreeWriteAllowed: false,
      localCommitAllowed: false,
      externalActionsAllowed: false,
    },
    capabilities: ['business-model', 'corporate-strategy', 'portfolio-planning'],
    enabled: false,
    executionMode: 'skeleton',
  },
  {
    id: 'nova',
    version: 1,
    name: 'Nova',
    displayName: 'Nova — Operations and Organization',
    description:
      'Operations advisor for organizational design, execution systems, and performance.',
    provider: 'anthropic',
    model: 'claude-sonnet-5',
    fallbackModels: [
      { provider: 'openai', model: 'gpt-5.6-terra' },
      { provider: 'anthropic', model: 'claude-opus-4-8' },
    ],
    reasoningEffort: 'medium',
    permissionTemplate: 'advisor',
    permissions: {
      networkReadAllowed: false,
      projectReadAllowed: true,
      artifactWriteAllowed: true,
      worktreeWriteAllowed: false,
      localCommitAllowed: false,
      externalActionsAllowed: false,
    },
    capabilities: ['operating-model', 'organizational-design', 'performance-management'],
    enabled: false,
    executionMode: 'skeleton',
  },
  {
    id: 'miro',
    version: 1,
    name: 'Miro',
    displayName: 'Miro — Market and Customer Growth',
    description:
      'Growth advisor for customer insight, market validation, pricing, and experiments.',
    provider: 'openai',
    model: 'gpt-5.6-terra',
    fallbackModels: [
      { provider: 'anthropic', model: 'claude-sonnet-5' },
      { provider: 'openai', model: 'gpt-5.6-sol' },
    ],
    reasoningEffort: 'medium',
    permissionTemplate: 'advisor',
    permissions: {
      networkReadAllowed: true,
      projectReadAllowed: true,
      artifactWriteAllowed: true,
      worktreeWriteAllowed: false,
      localCommitAllowed: false,
      externalActionsAllowed: false,
    },
    capabilities: ['customer-insight', 'growth-experiments', 'market-validation'],
    enabled: false,
    executionMode: 'skeleton',
  },
  {
    id: 'aegis',
    version: 1,
    name: 'Aegis',
    displayName: 'Aegis — Materials Science',
    description:
      'Materials science advisor for protective coatings, testing, durability, and safety.',
    provider: 'openai',
    model: 'gpt-5.6-sol',
    fallbackModels: [
      { provider: 'anthropic', model: 'claude-opus-4-8' },
      { provider: 'openai', model: 'gpt-5.6-terra' },
    ],
    reasoningEffort: 'xhigh',
    permissionTemplate: 'advisor',
    permissions: {
      networkReadAllowed: true,
      projectReadAllowed: true,
      artifactWriteAllowed: true,
      worktreeWriteAllowed: false,
      localCommitAllowed: false,
      externalActionsAllowed: false,
    },
    capabilities: ['coating-science', 'materials-testing', 'safety-review'],
    enabled: false,
    executionMode: 'skeleton',
  },
  {
    id: 'ledger',
    version: 1,
    name: 'Ledger',
    displayName: 'Ledger — Financial Advisory',
    description:
      'Financial advisor for investment analysis, cash flow, budgets, and risk assessment.',
    provider: 'anthropic',
    model: 'claude-opus-4-8',
    fallbackModels: [
      { provider: 'openai', model: 'gpt-5.6-sol' },
      { provider: 'anthropic', model: 'claude-sonnet-5' },
    ],
    reasoningEffort: 'high',
    permissionTemplate: 'advisor',
    permissions: {
      networkReadAllowed: false,
      projectReadAllowed: true,
      artifactWriteAllowed: true,
      worktreeWriteAllowed: false,
      localCommitAllowed: false,
      externalActionsAllowed: false,
    },
    capabilities: ['cash-flow', 'financial-analysis', 'investment-review'],
    enabled: false,
    executionMode: 'skeleton',
  },
  {
    id: 'forge',
    version: 1,
    name: 'Forge',
    displayName: 'Forge — Backend Engineering',
    description:
      'Backend engineering builder for servers, APIs, databases, authentication, and tests.',
    provider: 'anthropic',
    model: 'claude-sonnet-5',
    fallbackModels: [
      { provider: 'openai', model: 'gpt-5.6-terra' },
      { provider: 'anthropic', model: 'claude-opus-4-8' },
    ],
    reasoningEffort: 'high',
    permissionTemplate: 'builder',
    permissions: {
      networkReadAllowed: false,
      projectReadAllowed: true,
      artifactWriteAllowed: true,
      worktreeWriteAllowed: true,
      localCommitAllowed: true,
      externalActionsAllowed: false,
    },
    capabilities: ['api-development', 'backend-engineering', 'database-design'],
    enabled: false,
    executionMode: 'skeleton',
  },
  {
    id: 'luma',
    version: 1,
    name: 'Luma',
    displayName: 'Luma — Frontend Engineering',
    description:
      'Frontend engineering builder for interfaces, state management, accessibility, and APIs.',
    provider: 'anthropic',
    model: 'claude-sonnet-5',
    fallbackModels: [
      { provider: 'openai', model: 'gpt-5.6-terra' },
      { provider: 'anthropic', model: 'claude-opus-4-8' },
    ],
    reasoningEffort: 'high',
    permissionTemplate: 'builder',
    permissions: {
      networkReadAllowed: false,
      projectReadAllowed: true,
      artifactWriteAllowed: true,
      worktreeWriteAllowed: true,
      localCommitAllowed: true,
      externalActionsAllowed: false,
    },
    capabilities: ['accessibility', 'frontend-engineering', 'user-interface'],
    enabled: false,
    executionMode: 'skeleton',
  },
  {
    id: 'iris',
    version: 1,
    name: 'Iris',
    displayName: 'Iris — Design and UX/UI',
    description:
      'Design builder for user experience, information architecture, and interface specifications.',
    provider: 'anthropic',
    model: 'claude-fable-5',
    fallbackModels: [
      { provider: 'anthropic', model: 'claude-opus-4-8' },
      { provider: 'openai', model: 'gpt-5.6-sol' },
    ],
    reasoningEffort: 'high',
    permissionTemplate: 'builder',
    permissions: {
      networkReadAllowed: false,
      projectReadAllowed: true,
      artifactWriteAllowed: true,
      worktreeWriteAllowed: true,
      localCommitAllowed: true,
      externalActionsAllowed: false,
    },
    capabilities: ['design-systems', 'interaction-design', 'user-experience'],
    enabled: false,
    executionMode: 'skeleton',
  },
  {
    id: 'verify',
    version: 1,
    name: 'Verify',
    displayName: 'Verify — Functional and Automation QA',
    description:
      'Quality assurance writer for acceptance criteria, regression coverage, and automation.',
    provider: 'openai',
    model: 'gpt-5.6-terra',
    fallbackModels: [
      { provider: 'anthropic', model: 'claude-sonnet-5' },
      { provider: 'openai', model: 'gpt-5.6-sol' },
    ],
    reasoningEffort: 'high',
    permissionTemplate: 'qa_writer',
    permissions: {
      networkReadAllowed: false,
      projectReadAllowed: true,
      artifactWriteAllowed: true,
      worktreeWriteAllowed: true,
      localCommitAllowed: true,
      externalActionsAllowed: false,
    },
    capabilities: ['acceptance-testing', 'automation-qa', 'regression-testing'],
    enabled: false,
    executionMode: 'skeleton',
  },
  {
    id: 'sentinel',
    version: 1,
    name: 'Sentinel',
    displayName: 'Sentinel — Performance and Security QA',
    description:
      'Independent reviewer for performance, reliability, security, and exploratory quality risks.',
    provider: 'anthropic',
    model: 'claude-opus-4-8',
    fallbackModels: [
      { provider: 'openai', model: 'gpt-5.6-sol' },
      { provider: 'anthropic', model: 'claude-sonnet-5' },
    ],
    reasoningEffort: 'high',
    permissionTemplate: 'reviewer',
    permissions: {
      networkReadAllowed: false,
      projectReadAllowed: true,
      artifactWriteAllowed: true,
      worktreeWriteAllowed: false,
      localCommitAllowed: false,
      externalActionsAllowed: false,
    },
    capabilities: ['performance-review', 'security-review', 'test-strategy'],
    enabled: false,
    executionMode: 'skeleton',
  },
  {
    id: 'archon',
    version: 1,
    name: 'Archon',
    displayName: 'Archon — Technical Integration',
    description:
      'Technical integrator for architecture, engineering standards, security, and delivery.',
    provider: 'openai',
    model: 'gpt-5.6-sol',
    fallbackModels: [
      { provider: 'anthropic', model: 'claude-opus-4-8' },
      { provider: 'openai', model: 'gpt-5.6-terra' },
    ],
    reasoningEffort: 'xhigh',
    permissionTemplate: 'integrator',
    permissions: {
      networkReadAllowed: false,
      projectReadAllowed: true,
      artifactWriteAllowed: true,
      worktreeWriteAllowed: true,
      localCommitAllowed: true,
      externalActionsAllowed: false,
    },
    capabilities: ['architecture', 'engineering-standards', 'technical-integration'],
    enabled: false,
    executionMode: 'skeleton',
  },
  {
    id: 'orion',
    version: 1,
    name: 'Orion',
    displayName: 'Orion — Orchestration',
    description:
      'Primary orchestrator for work assignment, priorities, risk management, and synthesis.',
    provider: 'openai',
    model: 'gpt-5.6-sol',
    fallbackModels: [
      { provider: 'anthropic', model: 'claude-opus-4-8' },
      { provider: 'openai', model: 'gpt-5.6-terra' },
    ],
    reasoningEffort: 'xhigh',
    permissionTemplate: 'orchestrator',
    permissions: {
      networkReadAllowed: false,
      projectReadAllowed: true,
      artifactWriteAllowed: true,
      worktreeWriteAllowed: false,
      localCommitAllowed: false,
      externalActionsAllowed: false,
    },
    capabilities: ['coordination', 'risk-management', 'work-orchestration'],
    enabled: false,
    executionMode: 'skeleton',
  },
  {
    id: 'helios',
    version: 1,
    name: 'Helios',
    displayName: 'Helios — Manufacturing and Quality',
    description:
      'Manufacturing advisor for process scale-up, quality control, supply chain, and yield.',
    provider: 'anthropic',
    model: 'claude-opus-4-8',
    fallbackModels: [
      { provider: 'openai', model: 'gpt-5.6-sol' },
      { provider: 'anthropic', model: 'claude-sonnet-5' },
    ],
    reasoningEffort: 'high',
    permissionTemplate: 'advisor',
    permissions: {
      networkReadAllowed: false,
      projectReadAllowed: true,
      artifactWriteAllowed: true,
      worktreeWriteAllowed: false,
      localCommitAllowed: false,
      externalActionsAllowed: false,
    },
    capabilities: ['manufacturing-quality', 'process-scale-up', 'supply-chain'],
    enabled: false,
    executionMode: 'skeleton',
  },
  {
    id: 'regula',
    version: 1,
    name: 'Regula',
    displayName: 'Regula — Regulation and Compliance',
    description:
      'Compliance advisor for regulations, export controls, contracts, intellectual property, and risk.',
    provider: 'anthropic',
    model: 'claude-opus-4-8',
    fallbackModels: [
      { provider: 'openai', model: 'gpt-5.6-sol' },
      { provider: 'anthropic', model: 'claude-sonnet-5' },
    ],
    reasoningEffort: 'high',
    permissionTemplate: 'advisor',
    permissions: {
      networkReadAllowed: true,
      projectReadAllowed: true,
      artifactWriteAllowed: true,
      worktreeWriteAllowed: false,
      localCommitAllowed: false,
      externalActionsAllowed: false,
    },
    capabilities: ['compliance', 'export-control', 'intellectual-property'],
    enabled: false,
    executionMode: 'skeleton',
  },
  {
    id: 'insight',
    version: 1,
    name: 'Insight',
    displayName: 'Insight — Data and AI Intelligence',
    description:
      'Data strategy advisor for decision metrics, analysis methods, and responsible AI opportunities.',
    provider: 'openai',
    model: 'gpt-5.6-terra',
    fallbackModels: [
      { provider: 'anthropic', model: 'claude-sonnet-5' },
      { provider: 'openai', model: 'gpt-5.6-sol' },
    ],
    reasoningEffort: 'high',
    permissionTemplate: 'advisor',
    permissions: {
      networkReadAllowed: false,
      projectReadAllowed: true,
      artifactWriteAllowed: true,
      worktreeWriteAllowed: false,
      localCommitAllowed: false,
      externalActionsAllowed: false,
    },
    capabilities: ['analytics', 'data-strategy', 'responsible-ai'],
    enabled: false,
    executionMode: 'skeleton',
  },
  {
    id: 'keystone',
    version: 1,
    name: 'Keystone',
    displayName: 'Keystone — DevOps and SRE',
    description:
      'Platform builder for delivery automation, observability, recovery, and cloud security.',
    provider: 'anthropic',
    model: 'claude-sonnet-5',
    fallbackModels: [
      { provider: 'openai', model: 'gpt-5.6-terra' },
      { provider: 'anthropic', model: 'claude-opus-4-8' },
    ],
    reasoningEffort: 'high',
    permissionTemplate: 'builder',
    permissions: {
      networkReadAllowed: false,
      projectReadAllowed: true,
      artifactWriteAllowed: true,
      worktreeWriteAllowed: true,
      localCommitAllowed: true,
      externalActionsAllowed: false,
    },
    capabilities: ['cloud-security', 'devops', 'site-reliability'],
    enabled: false,
    executionMode: 'skeleton',
  },
  {
    id: 'nexus',
    version: 1,
    name: 'Nexus',
    displayName: 'Nexus — Product Ownership',
    description:
      'Product orchestrator for customer problems, requirements, priorities, and delivery plans.',
    provider: 'anthropic',
    model: 'claude-sonnet-5',
    fallbackModels: [
      { provider: 'openai', model: 'gpt-5.6-terra' },
      { provider: 'anthropic', model: 'claude-opus-4-8' },
    ],
    reasoningEffort: 'medium',
    permissionTemplate: 'orchestrator',
    permissions: {
      networkReadAllowed: false,
      projectReadAllowed: true,
      artifactWriteAllowed: true,
      worktreeWriteAllowed: false,
      localCommitAllowed: false,
      externalActionsAllowed: false,
    },
    capabilities: ['product-planning', 'requirements', 'roadmapping'],
    enabled: false,
    executionMode: 'skeleton',
  },
  {
    id: 'arca',
    version: 1,
    name: 'Arca',
    displayName: 'Arca — Internal Knowledge Registry',
    description:
      'Metadata-only knowledge registry for authorized source discovery, provenance, and lifecycle.',
    provider: 'anthropic',
    model: 'claude-sonnet-5',
    fallbackModels: [
      { provider: 'openai', model: 'gpt-5.6-terra' },
      { provider: 'anthropic', model: 'claude-opus-4-8' },
    ],
    reasoningEffort: 'medium',
    permissionTemplate: 'knowledge-registry',
    permissions: {
      networkReadAllowed: false,
      projectReadAllowed: true,
      artifactWriteAllowed: false,
      worktreeWriteAllowed: false,
      localCommitAllowed: false,
      externalActionsAllowed: false,
      registryProjectMetadataReadAllowed: true,
      registrySearchAllowed: true,
      sourceCardRegisterAllowed: true,
      sourceCardUpdateAllowed: true,
      purposeBoundExcerptReadAllowed: true,
      sourceRequestCreateAllowed: true,
      sourceRequestResolveAllowed: true,
      auditWriteAllowed: true,
      connectorReadAllowed: true,
      sourceCardArchiveWithApprovalAllowed: true,
      sourceRepositoryWriteAllowed: false,
      sourceFileDeleteMoveRenameAllowed: false,
      permissionChangeAllowed: false,
      classificationDowngradeAllowed: false,
      externalShareAllowed: false,
      archiveDeleteWithoutApprovalAllowed: false,
      sourceCardDeleteAllowed: false,
      arbitraryNetworkEndpointAllowed: false,
      registryOperationScopes: [
        'project-metadata-read',
        'registry-search',
        'sourcecard-register',
        'sourcecard-update',
        'purpose-bound-excerpt-read',
        'sourcerequest-create',
        'sourcerequest-resolve',
        'audit-write',
        'sourcecard-archive-with-approval',
      ],
    },
    capabilities: ['knowledge-registry', 'source-discovery'],
    enabled: false,
    executionMode: 'skeleton',
  },
];

export const agentProfileSeedSkeletons = deepFreeze(seedSkeletonDefinitions);
